# Uncomment the next line to define a global platform for your project
# platform :ios, '14.5'

target 'MyMemory' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyMemory
  pod 'Alamofire', '~> 5.4'

  target 'MyMemoryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyMemoryUITests' do
    # Pods for testing
  end

end
